version: '3'

services:
  dbfc:
    image: mysql:5.7
    command: ["--innodb-use-native-aio=0"]
    container_name: dbfc
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
  
  nodefc:
    container_name: nodefc
    build:
      context: ./node
    ports:
      - "3000:3000"
  
  nginx:
    container_name: nginxfc
    restart: always
    build:
      context: ./nginx
    ports:
        - "8080:80"


